backend:
  name: github
  repo: Strongman48553-maker/Godahab
  branch: main

media_folder: "photos"
public_folder: "/photos"

collections:
    - name: "tours"
    label: "الرحلات"
    folder: "photos"
    create: true
    slug: "{{slug}}"
    fields:
            - {label: "اسم الرحلة", name: "title", widget: "string"}
            - {label: "الصورة", name: "image", widget: "image"}
            - {label: "الوصف", name: "body", widget: "markdown"}
